name: Extrair HTML com Puppeteer

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL da página a extrair HTML'
        required: true
        type: string

jobs:
  puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install puppeteer

      - name: Executar script Puppeteer
        run: node script.js
        env:
          PAGE_URL: ${{ inputs.url }}
